featL Upgraded solution to dotnet 8
audaciaconsulting/Audacia.DataAccess pull request #1
Opened 2024-05-13 13:31 UTC by ShaziaBabarAudacia

| Action | Done? |
| --- | --- |
| Code compiles and unit tests all pass locally | ✔ |
| Debug/console log code removed | ✔ |
| Commented out code removed | ✔ |
| Unit tests added/updated | ❌ |
| README updated | ❌ |
| Considered: <br /> - Performance <br /> - Security <br /> - Logging | ✔ |
| Licenses of any new/upgraded dependencies checked, with no copyleft dependencies introduced | ✔ |

2024-05-17 10:30 UTC, jackpercy-acl requested changes
Thanks for sorting this Shaz 🙌 

As this will be a breaking change, please could you update all of the version numbers of the csproj files from 2.1.0 to 3.0.0?

2024-05-17 12:43 UTC, ShaziaBabarAudacia commented
Thanks @jackpercy-acl done :)

2024-05-17 12:44 UTC, jackpercy-acl approved these changes

2024-05-20 08:48 UTC, Audacia-RhysSmith commented
Nice work @ShaziaBabarAudacia!

2024-05-20 08:49 UTC, merged